openapi: 3.0.3
info:
  title: Viewer Telemetry API
  version: 1.0.0
servers:
  - url: http://localhost:8000
paths:
  /healthz:
    get:
      summary: Health check for FastAPI viewer service
      operationId: getHealthz
      responses:
        '200':
          description: Service healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [ok]
                  version:
                    type: string
                  timestamp:
                    type: string
                    format: date-time
        '503':
          description: Service unhealthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthError'
  /viewer-telemetry:
    post:
      summary: Ingest viewer telemetry events emitted from the Niivue frontend
      operationId: postViewerTelemetry
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ViewerTelemetryEvent'
      responses:
        '202':
          description: Telemetry accepted for processing
          content:
            application/json:
              schema:
                type: object
                properties:
                  requestId:
                    type: string
                    format: uuid
                  status:
                    type: string
                    enum: [accepted]
        '400':
          description: Payload validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        '429':
          description: Telemetry rate limited
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RateLimitError'
        '500':
          description: Unexpected ingestion failure
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerError'
components:
  schemas:
    ViewerTelemetryEvent:
      type: object
      required:
        - event
        - slideId
        - viewport
        - latencyMs
        - commandVersion
        - requestId
        - emittedAt
      properties:
        event:
          type: string
          enum: [viewer_launch, overlay_toggle, roi_draw, responsive_mode_change]
        slideId:
          type: string
          description: Matches SampleSlideBundle identifier
        viewport:
          type: object
          required: [zoom, pan, dpr, canvasSize]
          properties:
            zoom:
              type: number
              minimum: 0.01
              maximum: 20
            pan:
              type: object
              required: [x, y]
              properties:
                x: { type: number }
                y: { type: number }
            dpr:
              type: number
              minimum: 0.5
              maximum: 4
            canvasSize:
              type: object
              required: [width, height]
              properties:
                width: { type: integer, minimum: 1 }
                height: { type: integer, minimum: 1 }
        latencyMs:
          type: number
          minimum: 0
          maximum: 15000
        commandVersion:
          type: string
          description: Hash/version from README.md instructions
        requestId:
          type: string
          format: uuid
        emittedAt:
          type: string
          format: date-time
        telemetryVersion:
          type: string
          description: Optional semantic version for payload schema
        metadata:
          type: object
          additionalProperties: true
    ValidationError:
      type: object
      properties:
        error:
          type: string
        details:
          type: array
          items:
            type: string
    RateLimitError:
      type: object
      properties:
        error:
          type: string
        retryAfterSeconds:
          type: integer
    HealthError:
      type: object
      properties:
        status:
          type: string
        message:
          type: string
    ServerError:
      type: object
      properties:
        error:
          type: string
        requestId:
          type: string
          format: uuid
